export const BLOCKOUT_DATE = "BLOCKOUT_DATE";
export const VOLUNTEER_BLOCKOUT = "VOLUNTEER_BLOCKOUT";
export const VOLUNTEER_BLOCKOUT_REMOVE = "VOLUNTEER_BLOCKOUT_REMOVE";
export const SAVE_BLOCKOUT = "SAVE_BLOCKOUT";
export const SET_SCHEDULE = "SET_SCHEDULE";